version: '2'

networks: 
  envnetwork: 
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}

services:

### Workspace Utilities ##################################
  workspace:
    build: 
      context: ./workspace
      args:
        - PUID=${WORKSPACE_PUID}
        - PGID=${WORKSPACE_PGID}
        - TZ=${WORKSPACE_TIMEZONE}
    restart: always
    depends_on:
      - mysql
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    environment:
      - "DB_PORT:3306"
      - "DB_HOST:mysql"
    networks: 
      - envnetwork
  
### NGINX Server #########################################
  nginx:
    build:
      context: ./workspace
      dockerfile: Dockerfile-nginx
    volumes:
      - ./workspace/host.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    volumes_from:
      - workspace
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    networks: 
      - envnetwork

### MySQL ################################################
  mysql:
    build:
      context: ./workspace
      dockerfile: Dockerfile-mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    ports:
      - "${DB_PORT}:3306"
    networks: 
      - envnetwork

### PHPMyAdmin ################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    depends_on:
      - workspace
      - mysql
    links:
      - mysql 